#!/bin/bash

echo -e "------------------------------output exercise 2a round robin dispatcher------------------------------" > ./resultados/output2a_roundrobin.txt
echo -e "---Resultados de clientes ejercicio 2a dispatcher round robin---" > ./resultados/output2a_roundrobin_clientes.csv
echo -e "---Resultados de servidores ejercicio 2a dispatcher round robin---" > ./resultados/output2a_roundrobin_servidores.csv
echo "Cliente;Tiempo medio de servicio" >> ./resultados/output2a_roundrobin_clientes.csv
echo "Servidor;Tareas;Carga(%);Peticiones/s" >> ./resultados/output2a_roundrobin_servidores.csv
for i in {1..25}
	do
		mapfile -t output_array < <(./modelo2 platform-cluster.xml $(( i * 2 )) 10 roundrobin)
		for y in "${output_array[@]}"
			do
				echo -e "${y}" >> ./resultados/output2a_roundrobin.txt
				echo "${y}" | grep "Cliente" | sed -E 's/(Cliente[[:digit:]]*).*= ([[:digit:]]*\.*[[:digit:]]*).*/\1;\2/'  | sed -e 's/\./,/g' >> ./resultados/output2a_roundrobin_clientes.csv
				echo "${y}" | grep "Servidor" | sed -E 's/(Servidor[[:digit:]]*).*tareas: ([[:digit:]]*).*Carga: ([[:digit:]]*\.*[[:digit:]]*).*\/s: ([[:digit:]]*\.*[[:digit:]]*).*/\1;\2;\3;\4/' | sed -e 's/\./,/g' >> ./resultados/output2a_roundrobin_servidores.csv
				echo "${y}" | grep -E '^-*$' | sed -E 's/(^-*$)//' >> ./resultados/output2a_roundrobin_servidores.csv
				echo "${y}" | grep -E '^-*$' | sed -E 's/(^-*$)//' >> ./resultados/output2a_roundrobin_clientes.csv
			done 
	done
